server.port=9368

spring.datasource.url=jdbc:postgresql://localhost:5432/eCommerce?currentSchema=reddit
spring.datasource.username=ecommerce
spring.datasource.password=ecommerce
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.schema=reddit
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

############# Mail Properties ###########################################
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=457edfe5384fde
spring.mail.password=96f8c2d1805275
spring.mail.protocol=smtp

############ JWT Properties #####################
jwt.expiration.time=90000
jwt.public.key=classPath:app.pub
jwt.private.key=classPath:app.key

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v2/api-docs